- name: policy rule
  hosts: localhost
  tasks:

    - name: Canada App Connector Group 🚀
      willguibr.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Canada App Connector Group"
        description: "Canada App Connector Group"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        # version_profile_id: "{{ version.data[0].id }}"
      register: canada01_app_connector

    # - name: Segment Group - SGIO SIPA O365 🚀
    #   willguibr.zpacloud.zpa_segment_group:
    #     state: absent
    #     name: "SGIO SIPA O365"
    #     description: "SGIO SIPA O365"
    #     enabled: true
    #     config_space: "DEFAULT"
    #     policy_migrated: true
    #     tcp_keep_alive_enabled: "1"
    #   register: sg_sipa_o365

    - name: Server Group - SGIO SIPA O365 🚀
      willguibr.zpacloud.zpa_server_group:
        state: absent
        name: "SGIO SIPA O365"
        description: "SGIO SIPA O365"
        enabled: true
        dynamic_discovery: true
        app_connector_groups:
          - id: "{{ canada01_app_connector.data.id }}"
      register: srvg_sipa_o365

    # - name: Application Segment - SGIO SIPA O365 🚀
    #   willguibr.zpacloud.zpa_application_segment:
    #     state: absent
    #     name: "SGIO SIPA O365"
    #     description: "SGIO SIPA O365"
    #     enabled: true
    #     ip_anchored: true
    #     health_reporting: CONTINUOUS
    #     bypass_type: NEVER
    #     icmp_access_type: PING
    #     is_cname_enabled: true
    #     tcp_port_range:
    #       - from: "443"
    #         to: "443"
    #     domain_names:
    #       - "login.microsoftonline.com"
    #     segment_group_id: "{{ sg_sipa_o365.data.id }}"
    #     server_groups:
    #       - id: "{{ srvg_sipa_o365.data.id }}"
    #   register: app_seg_sipa_o365