- name: Service Edge Groups
  hosts: localhost
  tasks:
    - name: Gather information about all Service Edge Groups
      willguibr.zpacloud_ansible.zpa_service_edge_groups_info:
        name: "Canada Service Edge Group"
      register: service_edge

    - name: service edge group
      debug:
        msg: "{{ service_edge }}"

    - name: Create/update/delete an service edge groups
      willguibr.zpacloud_ansible.zpa_service_edge_groups:
        state: "absent"
        #id: "216196257331292046"
        name: "Example"
        description: "Example2"
        enabled: true
        city_country: "California, US"
        country_code: "US"
        latitude: "37.3382082"
        longitude: "-121.8863286"
        location: "San Jose, CA, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "0"
      register: service_edge

    - name: created appconnector group
      debug:
        msg: "{{ service_edge }}"
