- name: App Connector Controller
  hosts: localhost
  tasks:
    - name: Gather information about all App Connector Controllers
      willguibr.zpacloud.zpa_app_connector_controller_info:
        #name: "USA App Connector Group"
      register: result
      
    - debug:
        msg: "{{ result }}"

    - name: Verify App Connector Controller info fetched
      ansible.builtin.assert:
        that:
          - not result.changed
          - result.data is defined