- name: App Connector Groups
  hosts: localhost
  tasks:
    - name: Gather information about all App Connector Groups
      willguibr.zpacloud.zpa_app_connector_groups_info:
        name: "USA App Connector Group"
      register: app
    - name: app connector
      debug:
        msg: "{{ app }}"
    - name: Create/update/delete an app connector group
      willguibr.zpacloud.zpa_app_connector_groups:
        state: "absent"
        #id: "216196257331292046"
        name: "Example"
        description: "Example2"
        enabled: true
        city_country: "California, US"
        country_code: "US"
        latitude: "37.3382082"
        longitude: "-121.8863286"
        location: "San Jose, CA, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "0"
        dns_query_type: "IPV4"
      register: appconnectorg
    - name: created appconnector group
      debug:
        msg: "{{ appconnectorg }}"
