- name: policy rule
  hosts: localhost
  tasks:
    - name: Gather information about all policy rules
      willguibr.zpacloud_ansible.zpa_policy_access_rule_info:
        #id: "216196257331292020"
        name: "All Other Services"
      register: policy
    - name: policy rule
      debug:
        msg: "{{ policy }}"
    - name: Create/update/delete a policy rule
      willguibr.zpacloud_ansible.zpa_policy_access_rule:
        name: "test policy access rule"
        description: "test policy access rule"
        action: "ALLOW"
        rule_order: 2
        operator: "AND"
        conditions:
          - negated: false
            operator: "OR"
            operands:
              - name: "test policy access rule"
                object_type: "APP"
                lhs: "id"
                rhs: "216196257331291979"
        state: absent
      register: created_rule
    - name: created policy access rule
      debug:
        msg: "{{ created_rule }}"
