- name: server group
  hosts: localhost
  tasks:
    - name: Gather information about all server group
      willguibr.zpacloud_ansible.zpa_server_group_info:
        name: Browser Access Apps
        #id: 216196257331291969
      register: servers
    - name: servers
      debug:
        msg: "{{ servers }}"
    - name: Create an server group
      willguibr.zpacloud_ansible.zpa_server_group:
        state: absent
        name: "Example Test"
        description: "Example  Test"
        enabled: false
        dynamic_discovery: false
        app_connector_groups:
          - id: "216196257331291924"
        servers:
          - id: "216196257331291921"
        applications:
          - id: "216196257331291981"
      register: server_g
    - name: server group
      debug:
        msg: "{{ server_g }}"
