- name: SCIM Attribute
  hosts: localhost
  tasks:
    - name: Gather information about all SCIM Attribute
      willguibr.zpacloud_ansible.zpa_scim_attribute_header_info:
        # name: DepartmentName_SGIO-User-Okta
        # id: 216196257331282234
      register: scim
    - name: scim
      debug:
        msg: "{{ scim }}"
