- name: browser certificate
  hosts: localhost
  tasks:
    - name: Gather information about all browser certificate
      willguibr.zpacloud_ansible.zpa_ba_certificate_info:
        #name: Corp-Trusted-Networks
        id: "216196257331282583"
      register: certificates
    # - name: certificates

    - debug:
        msg: "{{ certificates }}"
