- name: LSS Controller
  hosts: localhost
  tasks:
    - name: Gather LSS Client Types
      willguibr.zpacloud.zpa_lss_client_types_info:
      register: client_types
    - name: client_types
      debug:
        msg: "{{ client_types }}"
    - name: Gather LSS Status Codes
      willguibr.zpacloud.zpa_lss_config_status_codes_info:
      register: status_codes
    - name: status_codes
      debug:
        msg: "{{ status_codes }}"
    - name: Gather LSS Log types formats
      willguibr.zpacloud.zpa_lss_config_log_types_formats_info:
        log_type: zpn_trans_log
      register: log_types_formats
    - name: log_types_formats
      debug:
        msg: "{{ log_types_formats }}"
    # - name: Create a LSS Controller
    #   willguibr.zpacloud.zpa_lss_config_controller:
    #     state: absent
    #     config:
    #       name: Status
    #       description: status
    #       enabled: true
    #       lss_host: 10.1.1.1
    #       lss_port: 20000
    #       source_log_type: "zpn_ast_auth_log"
    #   register: lss_controller
    # - name: lss_controller
    #   debug:
    #     msg: "{{ lss_controller }}"
