- name: App Connector Groups
  hosts: localhost
  tasks:
    - name: Gather information about all App Connector Groups
      willguibr.zpacloud.zpa_app_connector_groups_info:
        name: "USA App Connector Group"
      register: result
    # - name: app connector
    #   debug:
    #     msg: "{{ app }}"

    - name: Verify app connector group info fetched
      ansible.builtin.assert:
        that:
          - not result.changed
          - result.data is defined