- name: customer version profile
  hosts: localhost
  tasks:
    - name: Gather information about all customer version profile
      willguibr.zpacloud_ansible.zpa_customer_version_profile_info:
        name: "New Release"
        # id: 216196257331282234
      register: version
    - name: version
      debug:
        msg: "{{ version }}"
