- name: SAML Attribute
  hosts: localhost
  tasks:
    - name: Gather information about all SAML Attribute
      willguibr.zpacloud_ansible.zpa_saml_attribute_info:
        name: DepartmentName_SGIO-User-Okta
        # id: 216196257331282234
      register: saml
    - name: saml
      debug:
        msg: "{{ saml }}"
