- name: Application Server
  hosts: localhost

  tasks:
    - name: Gather information about all Application Servers
      willguibr.zpacloud.zpa_application_server_info:
        # name: "jenkins.securitygeek.io"
      register: app_server
    - name: application server
      debug:
        msg: "{{ app_server }}"

    - name: Create a segment group
      willguibr.zpacloud.zpa_application_server:
        state: absent
        name: "Example Application Server"
        address: "test.securitygeek.io"
        enabled: true
        description: "Example Application Server"
        config_space: "DEFAULT"
        app_server_group_ids: [216196257331292104, 216196257331291965]
      register: application_server
    - name: created/updated application server
      debug:
        msg: "{{ application_server }}"