- name: machine groups
  hosts: localhost
  tasks:
    - name: Gather information about all machine groups
      willguibr.zpacloud.zpa_machine_group_info:
        #name: Corp-Trusted-Networks
        # id: 216196257331282234
      register: machine_groups
    - name: machine_groups
      debug:
        msg: "{{ machine_groups }}"
