- name: Application Server
  hosts: localhost

  tasks:
    # - name: Gather information about all Application Servers
    #   willguibr.zpacloud_ansible.zpa_application_server_info:
    #     # name: "jenkins.securitygeek.io"
    #   register: app_server
    # - name: application server

    #   debug:
    #     msg: "{{ app_server }}"

    - name: Create a segment group
      willguibr.zpacloud_ansible.zpa_application_server:
        # state: absent
        name: "Example Application Server"
        address: "test.securitygeek.io"
        enabled: true
        description: "Example Application Server"
        config_space: "DEFAULT"
        app_server_group_ids: 
          - id: "216196257331291967"
      register: application_server

    - debug:
        msg: "{{ application_server }}"