- name: trusted network
  hosts: localhost
  tasks:
    - name: Gather information about all trusted network
      willguibr.zpacloud_ansible.zpa_trusted_network_info:
        #name: Corp-Trusted-Networks
        id: 216196257331282234
      register: networks
    - name: networks
      debug:
        msg: "{{ networks }}"
