- name: Cloud Connector Group
  hosts: localhost
  tasks:
    - name: Gather information about all Cloud Connector Group
      willguibr.zpacloud_ansible.zpa_cloud_connector_group_info:
        #name: zs-cc-vpc-096108eb5d9e68d71-ca-central-1a
        id: 216196257331292017
      register: cloud_connector
    - name: cloud_connector
      debug:
        msg: "{{ cloud_connector }}"
