- name: IDP Controller
  hosts: localhost
  tasks:
    - name: Gather information about all IDP Controller
      willguibr.zpacloud_ansible.zpa_idp_controller_info:
        name: SGIO-User-Okta
        # id: 216196257331282234
      register: idps
    - name: idps
      debug:
        msg: "{{ idps }}"
