- name: App Connector Groups
  hosts: localhost
  tasks:
    # - name: Gather information about all App Connector Groups
    #   willguibr.zpacloud.zpa_app_connector_groups_info:
    #     name: "USA App Connector Group"
    #   register: result

    # - debug:
    #     msg: "{{ result.changed }}"

# Create App Connector Groups (Absent)
    - name: Ensure App Connector Group is absent (leftover)
      willguibr.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      ignore_errors: true  # In case one was left from previous run
      register: result

    - name: Ensure App Connector Group is absent
      willguibr.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      register: result

    - name: Verify App Connector Group is absent
      ansible.builtin.assert:
        that:
          - not result.changed

# Create App Connector Groups (Present)
    - name: Example (Present)
      willguibr.zpacloud.zpa_app_connector_groups:
        state: present
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      register: result

    - name: Verify app connector group is present
      ansible.builtin.assert:
        that:
            - result.data
            - result.data.name is defined
            - result.data.enabled is true

    - name: Create the App Connector Group (again; idempotency check)
      willguibr.zpacloud.zpa_app_connector_groups:
        state: present
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      register: result

    - name: Verify App Connector Group is present
      ansible.builtin.assert:
        that:
          - result.changed

    - name: Fetch all App Connector Groups
      willguibr.zpacloud.zpa_app_connector_groups_info:
      register: result

    - name: Ensure all App Connector Groups found
      ansible.builtin.assert:
        that:
          - not result.changed
          - result.data[0] is defined

    - name: Fetch this App Connector Group
      willguibr.zpacloud.zpa_app_connector_groups_info:
        name: "Example"
      register: result

    - name: Ensure all App Connector Groups found
      ansible.builtin.assert:
        that:
          - result.data[0] is defined
          - result.data | length == 1
          - result.data[0].name is defined

    - name: Give the ZPA Cloud a 5 seconds to settle
      ansible.builtin.pause:
        seconds: 5

    - name: Delete App Connector Group
      willguibr.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      register: result

    - name: Verify App Connector Group is absent
      ansible.builtin.assert:
        that:
          - not result.changed

    - name: Delete App Connector Group (again; idempotency check)
      willguibr.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
      register: result

    - name: Verify App Connector Group is absent
      ansible.builtin.assert:
        that:
          - not result.changed