- name: provisioning key
  hosts: localhost
  tasks:
    - name: Gather information about all provisioning keys
      willguibr.zpacloud_ansible.zpa_provisioning_key_info:
        id: "8691"
        #name: "USA App Connector Group"
        association_type: "CONNECTOR_GRP"
      register: keys
    - name: provisioning key
      debug:
        msg: "{{ keys }}"
    - name: Create/update/delete a Provisioning Key
      willguibr.zpacloud_ansible.zpa_provisioning_key:
        name: "New York Provisioning Key"
        association_type: "CONNECTOR_GRP"
        max_usage: "10"
        enrollment_cert_id: 6573
        zcomponent_id: 216196257331291903
        state: absent
      register: created_key
    - name: created key
      debug:
        msg: "{{ created_key }}"
