- name: App segment
  hosts: localhost
  tasks:
    - name: Gather information about all App segment
      willguibr.zpacloud_ansible.zpa_application_segment_info:
        #id: "216196257331291981"
      register: app
    - name: app segment
      debug:
        msg: "{{ app }}"
    - name: Create an app segment
      willguibr.zpacloud_ansible.zpa_application_segment:
        state: absent
        name: Example Application
        description: Example Application Test
        enabled: true
        health_reporting: ON_ACCESS
        bypass_type: NEVER
        is_cname_enabled: true
        tcp_port_range:
          - from: "80"
            to: "80"
        domain_names:
          - crm.example.com
        segment_group_id: "216196257331291896"
        server_groups:
          - id: "216196257331291969"
          #- id: "216196257331291962"
      register: app_segment
    - name: created/updated app segment
      debug:
        msg: "{{ app_segment }}"