- name: Segment Group
  hosts: localhost
  tasks:
    - name: Gather information about all Segment Groups
      willguibr.zpacloud.zpa_segment_group_info:
        #name: "Browser Access Apps"
      register: segment_group
    - name: segment group
      debug:
        msg: "{{ segment_group }}"
    - name: Create a segment group
      willguibr.zpacloud.zpa_segment_group:
        state: absent
        config_space: "DEFAULT"
        name: Example Segment Group
        description: Example Segment Group
        enabled: true
        policy_migrated: true
        tcp_keep_alive_enabled: "1"
        applications:
          #- id: "216196257331291980"
      register: segment_group
    - name: created/updated segment group
      debug:
        msg: "{{ segment_group }}"