- name: policy rule
  hosts: localhost

  tasks:
    - name: Gather information about all machine groups
      willguibr.zpacloud.zpa_trusted_networks_info:
        name: Corp-Trusted-Networks
      register: network_id
    - debug:
        msg: "{{ network_id.data[0].network_id }}"

    - name: Create/update/delete a policy rule
      willguibr.zpacloud.zpa_policy_access_rule:
        name: "test policy access rule"
        description: "test policy access rule"
        action: "ALLOW"
        rule_order: 2
        operator: "AND"
        conditions:
          - negated: false
            operator: "OR"
            operands:
              - name: "test policy access rule"
                object_type: "TRUSTED_NETWORK"
                lhs: "{{ network_id.data[0].network_id }}"
                rhs: "true"
        state: absent
      register: created_rule
    - name: created policy access rule
      debug:
        msg: "{{ created_rule }}"
