- name: Posture Profile
  hosts: localhost
  tasks:
    - name: Gather information about all Posture Profiles
      willguibr.zpacloud_ansible.zpa_posture_profile_info:
        #name: Corp-Trusted-Networks
        # id: 216196257331285223
      register: postures
    - name: postures
      debug:
        msg: "{{ postures }}"
