name: integration
on:
  # ! Don't enable pwn requests !
  # pull_request:
  push:
    branches:
      - ci*
      - main
  schedule:
    - cron: "10 6 * * *"

concurrency:
  group: cloud-integration-tests
  cancel-in-progress: false

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Perform testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          # ansible-core-version:
          pre-test-cmd: >- # Configure integration test run
            ZPA_CLIENT_ID=${{ secrets.ZPA_CLIENT_ID }}
            ZPA_CLIENT_SECRET=${{ secrets.ZPA_CLIENT_SECRET }}
            ZPA_CUSTOMER_ID=${{ secrets.ZPA_CUSTOMER_ID }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          python-version: 3.9
          target-python-version: 3.9
          testing-type: integration
          test-deps: community.general
